#!/usr/bin/perl

use XML::Parser;

sub start {
        my ($expat, $element, %tags) = @_;

	if ($element eq "changeset") {
		$date = $tags{'created_at'};
		$date =~ s/T.*//;

		$changesets = $tags{'num_changes'};
		$who = $tags{'user'};
		# print "found $who\n";

		if ($date ne $odate) {
			for $k (keys(%sum)) {
				@users = keys(%{$users{$k}});
				# print "got @users\n";
				$nusers = $#users + 1;

				print "$sum{$k} $k $changesum{$k} $nusers\n";
			}

			%sum = ();
			%changesum = ();
			%users = ();
			$odate = $date;
		}

		$editor = "unknown";
	} elsif ($element eq "tag") {
		if ($tags{'k'} eq "created_by") {
			$editor = $tags{'v'};

			$editor =~ s/ \(.*//; # get rid of JOSM language/build codes
			$editor =~ tr/ /_/;
		}
	}
}

sub end {
	my ($expat, $element) = @_;

	if ($element eq "changeset") {
		if ($editor ne "unknown") {
			$sum{"$date $editor"}++;
			$changesum{"$date $editor"} += $changesets;
			$users{"$date $editor"}{$who} = 1;
		}

		$date = "";
		$editor = "unknown";
	}
}

new XML::Parser(Handlers => { Start => \&start, End => \&end })->parse(*STDIN);
