#!/usr/bin/perl

use XML::Parser;

sub start {
        my ($expat, $element, %tags) = @_;

	if ($element eq "changeset") {
		$date = $tags{'created_at'};
		$date =~ s/T.*//;

		if ($date ne $odate) {
			for $k (keys(%sum)) {
				print "$sum{$k} $k\n";
			}

			%sum = ();
			$odate = $date;
		}

		$editor = "unknown";
	} elsif ($element eq "tag") {
		if ($tags{'k'} eq "created_by") {
			$editor = $tags{'v'};

			$editor =~ s/ \(.*//; # get rid of JOSM language/build codes
		}
	}
}

sub end {
	my ($expat, $element) = @_;

	if ($element eq "changeset") {
		if ($editor ne "unknown") {
			$sum{"$date $editor"}++;
		}

		$date = "";
		$editor = "unknown";
	}
}

new XML::Parser(Handlers => { Start => \&start, End => \&end })->parse(*STDIN);
